# Processes: each one is a small zoomable diagram of real screens in order,
# the button pressed marked on each, plus boxes for what the server does.
import json, os
D = os.path.dirname(os.path.abspath(__file__))
L, DP, K = 'asLearner();', 'asDept();', 'asKey();'
OUT = 'state.user=null; state.session=null; state.needsProfile=false; state.needsConsent=false; state.googleEnabled=true;'
DRAFT = '{ email:"jan.smit@voorbeeld.co.za", name:"Jan", surname:"Smit", grade:"Graad 11", gender:"Seun", popia:true }'

# Screens the processes need: id -> (setup, full height?, extra js after render)
SHOTS = {
  "p-signup": (OUT + f'state.auth={{ mode:"signup", step:"details", draft:{DRAFT} }};', True, ''),
  "p-signup-err": (OUT + f'state.auth={{ mode:"signup", step:"details", draft:{DRAFT} }};', True,
                   'showErrors(document.querySelector(\'[data-form="auth-details"]\'), { email:"Hierdie e-posadres is reeds geregistreer. Kies \\"Teken in\\" hierbo." });'),
  "p-signin": (OUT + 'state.auth={ mode:"signin", step:"details", draft:{ email:"jan.smit@voorbeeld.co.za" } };', True, ''),
  "p-code": (OUT + 'state.auth={ mode:"signin", step:"code", draft:{ email:"jan.smit@voorbeeld.co.za" } };', False, 'document.querySelector(\'[name="code"]\').value="482915";'),
  "p-code-err": (OUT + 'state.auth={ mode:"signin", step:"code", draft:{ email:"jan.smit@voorbeeld.co.za" } };', False,
                 'document.querySelector(\'[name="code"]\').value="482951"; showErrors(document.querySelector(\'[data-form="auth-code"]\'), { code:"Die kode is verkeerd of het verval. Probeer weer of vra \'n nuwe kode." });'),
  "p-profile": ('state.user=null; state.needsConsent=false; state.session={ user:{ id:"u1", email:"jan.smit@gmail.com", user_metadata:{ full_name:"Jan Smit" } } }; state.needsProfile=true;', True, ''),
  "p-loader": ('state.user=null; state.session=null; state.loading=true;', False, ''),
  "p-kalender": (L + 'state.tab="calendar"; state.calView="week"; goToDate(TODAY);', False, ''),
  "p-pushask": (L + 'state.tab="calendar"; state.calView="week"; goToDate(TODAY);', False, 'openPushAsk();'),
  "p-install": (L + 'state.tab="calendar";', False, 'openInstallHelp();'),
  "p-install-iphone": (L + 'state.tab="calendar";', False, 'openInstallHelp(); document.querySelector(\'[data-phone="iphone"]\').click();'),
  "p-kalender-a": (DP + 'state.tab="calendar"; state.calView="week"; goToDate(TODAY);', False, ''),
  "p-skep": (DP + 'state.tab="create"; state.editingId=null;', True, 'document.querySelector(\'[name="title"]\').value="Netbal: Garsies teen Menlo"; document.querySelector(\'[name="venue"]\').value="Netbalbane"; const nb=document.querySelector(".notify-box"); if (nb) nb.open=true;'),
  "p-skep-err": (DP + 'state.tab="create"; state.editingId=null;', True,
                 'showErrors(document.querySelector(\'[data-form="event"]\'), { title:"Gee die geleentheid \'n naam.", end:"Die einde moet ná die begin wees." });'),
  "p-edit": (DP + 'state.tab="create"; state.editingId=1;', True, ''),
  "p-admin-ev": (DP + 'state.tab="calendar"; state.openEventId=1;', False, ''),
  "p-admin-ev2": (DP + 'state.tab="calendar"; state.openEventId=2;', False, ''),
  "p-ev-open": (L + 'state.tab="calendar"; state.openEventId=6;', False, ''),
  "p-ev-booked": (L + 'state.tab="calendar"; state.supported.add(6); state.openEventId=6;', False, ''),
  "p-ev-invited": (L + 'state.tab="calendar"; state.openEventId=2;', False, ''),
  "p-myprogram": (L + 'state.tab="mine"; state.inboxOpen=false; state.supported.add(6);', False, ''),
  "p-inbox": (L + 'state.tab="mine"; state.inboxOpen=true;', False, ''),
  "p-myprogram-acc": (L + 'state.tab="mine"; state.inboxOpen=false; INVITES={2:"accepted"}; state.supported.add(2);', False, ''),
  "p-kaart-idle": (L + 'state.tab="map"; state.mapMode="map"; state.mapEventId=1; geo.status="idle"; geo.pos=null;', False, ''),
  "p-kaart-far": (L + 'state.tab="map"; state.mapMode="map"; state.mapEventId=1; geo.status="on"; geo.pos={lat:-25.8065,lng:28.3055,accuracy:15};', False, ''),
  "p-kaart-in": (L + 'state.tab="map"; state.mapMode="map"; state.mapEventId=1; geo.status="on"; geo.pos={lat:-25.79735,lng:28.30550,accuracy:12};', False, ''),
  "p-kaart-done": (L + 'state.tab="map"; state.mapMode="map"; state.mapEventId=1; geo.status="on"; geo.pos={lat:-25.79735,lng:28.30550,accuracy:12}; CHECKINS[1]={ at:"2026-10-10T13:58:00", method:"gps", distance:20, flags:[] };', False, ''),
  "p-qr-idle": (L + 'state.tab="map"; state.mapMode="qr"; state.scan={status:"idle",message:""};', False, ''),
  "p-qr-ok": (L + 'state.tab="map"; state.mapMode="qr"; state.scan={status:"ok",message:"Jy is aangemeld by Rugby: Garsies teen Affies!"};', False, ''),
  "p-qr-err": (L + 'state.tab="map"; state.mapMode="qr"; state.scan={status:"error",message:"Jy is 1,2 km van die geleentheid af. Jy moet binne die area wees om aan te meld."};', False, ''),
  "p-qr-queued": (L + 'state.tab="map"; state.mapMode="qr"; state.scan={status:"queued",message:"Gestoor! Jy word aangemeld sodra jy weer internet het."};', False, ''),
  "p-qr-admin": (DP + 'state.tab="calendar"; state.qrEventId=1; state.qrMode="live";', False, ''),
  "p-nooi": (DP + 'state.tab="calendar"; state.openEventId=2; state.inviteEventId=2; state.inviteResult="";', False,
             'document.querySelector(\'#groups-box input[value="g2"]\').checked=true;'),
  "p-nooi-done": (DP + 'state.tab="calendar"; state.openEventId=2; state.inviteEventId=2; state.inviteResult=peopleResult("<b>22</b> mense genooi · 2 was reeds genooi.", ["onbekend@voorbeeld.co.za"]);', False, ''),
  "p-bestuur": (DP + 'state.tab="manage"; state.manageGroupId=null;', True, ''),
  "p-groep": (DP + 'state.tab="manage"; state.manageGroupId="g2"; state.memberList={key:"g2", rows:MEMBERS};', True, 'TYPE:#person-search:pie'),
  "p-groep-done": (DP + 'state.tab="manage"; state.manageGroupId="g2"; state.groupResult=""; state.memberList={key:"g2", rows:[...MEMBERS, { user_id:"p2", name:"Pieta", surname:"Smit", grade:"Graad 9", gender:"Meisie", email:"pieta.smit@voorbeeld.co.za" }]};', True, ''),
  "p-instellings": (L + 'state.settingsOpen=true; state.settingsPage=null;', True, ''),
  "p-instellings-on": (L + 'state.settingsOpen=true; state.settingsPage=null; state.push={status:"on",busy:false};', False, ''),
  "p-cal-off": (L + 'state.settingsOpen=true; state.settingsPage=null; state.calFeed=null;', True, ''),
  "p-cal-on": (L + 'state.settingsOpen=true; state.settingsPage=null; state.calFeed="abcdef0123456789abcdef0123456789abcd";', True, ''),
  "p-volg": (L + 'state.settingsOpen=true; state.settingsPage="follow";', False, ''),
  "p-delete": (L + 'state.settingsOpen=true; state.settingsPage=null;', False, 'openDeleteAccount();'),
  "p-key-instellings": (K + 'state.settingsOpen=true; state.settingsPage=null;', True, ''),
  "p-leerder-edit": (K + 'state.settingsOpen=true; state.settingsPage="learner"; state.learnerEdit={ email:"jan.smit@voorbeeld.co.za", name:"Jan", surname:"Smit", grade:"Graad 11", gender:"Seun" };', True, ''),
  "p-preview": (K + 'state.settingsOpen=true; state.settingsPage="preview";', False, ''),
  "p-preview-on": (K + 'startPreview("Graad 9", "Meisie");', False, ''),
}

def scr(n, shot, col, row, marks=(), cap=""): return dict(n=n, kind="screen", shot=shot, col=col, row=row, marks=list(marks), cap=cap)
def box(n, kind, col, row, title, text=""): return dict(n=n, kind=kind, col=col, row=row, title=title, text=text)

PROCS = [
 dict(id="registreer", title="Registreer", who="Besoeker", summary="'n Nuwe leerder, ouer of alumnus maak 'n rekening met 'n e-poskode; geen wagwoord nie.",
  nodes=[scr("a", "p-signup", 0, 0, [('[data-action="auth-mode-signup"]', "Registreer"), ('[name="email"]', "E-pos"), ('[name="grade"]', "Graad (en geslag)"), ('[name="popia"]', "Privaatheid aanvaar"), ('[data-form="auth-details"] [type="submit"]', "Stuur kode")], "Vul die vorm in"),
         box("b", "q", 1, 0, "Reeds geregistreer?", "Die bediener kyk die e-posadres."),
         scr("c", "p-signup-err", 1, 1, [('.field-error', "Foutboodskap")], "Ja: kies Teken in"),
         box("d", "ext", 2, 0, "E-pos met 6-syferkode", "Kom binne 'n minuut; kyk ook in spam."),
         scr("e", "p-code", 3, 0, [('[name="code"]', "Kode"), ('[data-form="auth-code"] [type="submit"]', "Bevestig"), ('[data-action="auth-resend"]', "Stuur weer")], "Tik die kode"),
         box("f", "q", 4, 0, "Kode reg?", ""),
         scr("g", "p-code-err", 4, 1, [('.field-error', "Foutboodskap")], "Nee: probeer weer"),
         box("h", "db", 5, 0, "Profiel geskep", "Naam, graad, geslag en die tyd van POPIA-toestemming word gestoor."),
         scr("i", "p-loader", 6, 0, [], "Laai-animasie"),
         scr("j", "p-install", 7, 0, [('[data-phone="iphone"]', "Kies jou foon")], "Op 'n foon: sit op tuisskerm"),
         scr("k", "p-pushask", 8, 0, [('#push-ask [data-yes]', "Skakel aan")], "Vra vir kennisgewings"),
         scr("l", "p-kalender", 9, 0, [], "Klaar: kalender")],
  edges=[("a", 4, "b", "Stuur kode"), ("b", None, "c", "Ja"), ("b", None, "d", "Nee"), ("d", None, "e", ""), ("e", 1, "f", "Bevestig"),
         ("f", None, "g", "Nee"), ("f", None, "h", "Ja"), ("h", None, "i", ""), ("i", None, "j", ""), ("j", None, "k", "Nie nou nie / klaar"), ("k", None, "l", "")]),
 dict(id="teken-in", title="Teken in", who="Besoeker", summary="Iemand met 'n rekening teken in met 'n e-poskode, of met Google.",
  nodes=[scr("a", "p-signin", 0, 0, [('[data-action="auth-mode-signin"]', "Teken in"), ('[name="email"]', "E-pos"), ('[data-form="auth-details"] [type="submit"]', "Stuur kode"), ('[data-action="auth-google"]', "Google")], "E-pos of Google"),
         box("b", "ext", 1, 0, "E-pos met 6-syferkode", ""),
         scr("c", "p-code", 2, 0, [('[name="code"]', "Kode"), ('[data-form="auth-code"] [type="submit"]', "Bevestig")], "Tik die kode"),
         box("g1", "ext", 1, 1, "Google-aanmelding", "Google stuur net naam en e-pos."),
         box("g2", "q", 2, 1, "Eerste keer?", ""),
         scr("g3", "p-profile", 3, 1, [('[name="grade"]', "Graad (en geslag)"), ('[name="popia"]', "Privaatheid aanvaar"), ('[data-form="profile"] [type="submit"]', "Gaan voort")], "Voltooi profiel"),
         scr("d", "p-loader", 4, 0, [], "Laai"),
         scr("e", "p-kalender", 5, 0, [], "Kalender")],
  edges=[("a", 2, "b", "Stuur kode"), ("b", None, "c", ""), ("c", 1, "d", "Bevestig"), ("a", 3, "g1", "Gaan voort met Google"), ("g1", None, "g2", ""),
         ("g2", None, "g3", "Ja"), ("g2", None, "d", "Nee"), ("g3", 2, "d", "Gaan voort"), ("d", None, "e", "")]),
 dict(id="skep", title="Skep geleentheid", who="Departement-admin, Hoof-admin", summary="Van die + knoppie tot die kennisgewings wat uitgaan.",
  nodes=[scr("a", "p-kalender-a", 0, 0, [('[data-action="new-event"]', "+ (of Skep-oortjie)")], "Kalender"),
         scr("b", "p-skep", 1, 0, [('[name="title"]', "Titel"), ('#group-select', "Subafdeling"), ('#pick-map', "Plek en sirkel"), ('[name="radius"]', "Radius"), ('[name="inviteOnly"]', "Wie mag kom"), ('.notify-box > summary', "Wie kry 'n kennisgewing"), ('[data-form="event"] [type="submit"]', "Skep geleentheid")], "Vul die vorm in"),
         box("c", "q", 2, 0, "Alles reg?", "Naam, datum, tye, plek en radius word nagegaan."),
         scr("d", "p-skep-err", 2, 1, [('.field-error', "Foute langs die velde")], "Nee: niks word gestoor nie"),
         box("e", "db", 3, 0, "Geleentheid gestoor", "Die bediener kyk weer of jy hierdie afdeling mag bestuur."),
         box("f", "q", 4, 0, "Wie mag dit sien?", "Net hulle kry die kennisgewing."),
         box("g", "inbox", 5, 0, "Inbox: Nuwe geleentheid", ""),
         box("h", "push", 5, 1, "Push", "Net toestelle met kennisgewings aan."),
         box("i", "ok", 6, 0, "Kalender spring na die datum", "\"Geskep · 42 kennisgewings\"")],
  edges=[("a", 0, "b", "+"), ("b", 6, "c", "Skep"), ("c", None, "d", "Nee"), ("c", None, "e", "Ja"), ("e", None, "f", "Kennisgewings"),
         ("f", None, "g", ""), ("f", None, "h", ""), ("e", None, "i", "")]),
 dict(id="wysig", title="Wysig of skrap 'n geleentheid", who="Departement-admin, Hoof-admin", summary="Veranderings en kansellasies gaan outomaties na almal wat bespreek het.",
  nodes=[scr("a", "p-admin-ev", 0, 0, [('[data-action="edit-event"]', "Wysig")], "Geleentheid (admin)"),
         scr("b", "p-edit", 1, 0, [('[name="date"]', "Datum"), ('[name="start"]', "Tyd"), ('[name="venue"]', "Plek"), ('[data-form="event"] [type="submit"]', "Stoor veranderinge")], "Wysig"),
         box("c", "q", 2, 0, "Tyd, plek of naam verander?", ""),
         box("d", "inbox", 3, 0, "Inbox: Verandering", "Aan almal wat bespreek het."),
         box("e", "push", 3, 1, "Push", ""),
         box("f", "ok", 2, 1, "Net gestoor", "Ander velde: geen boodskap nie."),
         box("s1", "q", 1, 1, "Skrap? (Skep-lys)", "Die app vra eers of jy seker is."),
         box("s2", "inbox", 1, 2, "Inbox: Gekanselleer", "Aan almal wat bespreek het; besprekings, uitnodigings en aanmeldings word ook geskrap.")],
  edges=[("a", 0, "b", "Wysig"), ("b", 3, "c", "Stoor"), ("c", None, "d", "Ja"), ("c", None, "e", "Ja"), ("c", None, "f", "Nee"), ("s1", None, "s2", "Ja")]),
 dict(id="bespreek", title="Bespreek", who="Leerder, alumnus, ouer, admins", summary="Een tik; die herinnering en veranderings kom outomaties.",
  nodes=[scr("a", "p-kalender", 0, 0, [('.block', "Geleentheid")], "Kalender of Soek"),
         scr("b", "p-ev-open", 1, 0, [('[data-action="toggle-support"]', "Bespreek")], "Geleentheid"),
         box("c", "db", 2, 0, "Bespreking gestoor", "Telling en Excel van die admin word bygewerk."),
         scr("d", "p-ev-booked", 3, 0, [('[data-action="toggle-support"]', "Jy het bespreek (tik weer om te kanselleer)")], "Bespreek"),
         scr("e", "p-myprogram", 4, 0, [('.mine-grid [data-event]', "In My program")], "My program"),
         box("f", "push", 5, 0, "1 uur voor: herinnering", "")],
  edges=[("a", 0, "b", "Tik"), ("b", 0, "c", "Bespreek"), ("c", None, "d", ""), ("d", None, "e", ""), ("e", None, "f", "")]),
 dict(id="aanmeld-gps", title="Aanmeld met die Kaart (GPS)", who="Leerder, alumnus, ouer", summary="Werk net binne die sirkel; offline word dit gestoor en later gestuur.",
  nodes=[scr("a", "p-kaart-idle", 0, 0, [('[data-action="start-location"]', "Deel my ligging")], "Eerste keer"),
         box("b", "phone", 1, 0, "Foon vra toestemming", "Ligging toelaat."),
         scr("c", "p-kaart-far", 2, 0, [('.btn-checkin', "Kom nader (af)")], "Buite die sirkel"),
         scr("d", "p-kaart-in", 3, 0, [('[data-action="checkin"]', "Meld aan")], "Binne die sirkel"),
         box("e", "q", 4, 0, "Internet?", ""),
         box("f", "phone", 4, 1, "Op die foon gestoor", "Word gestuur sodra daar internet is."),
         box("g", "db", 5, 0, "Bediener kyk weer", "Afstand, wie mag kom, reeds aangemeld."),
         scr("h", "p-kaart-done", 6, 0, [('.btn-checkin', "Aangemeld")], "Klaar")],
  edges=[("a", 0, "b", "Tik"), ("b", None, "c", "Toegelaat"), ("c", None, "d", "Loop nader"), ("d", 0, "e", "Meld aan"), ("e", None, "f", "Nee"),
         ("e", None, "g", "Ja"), ("f", None, "g", "Later"), ("g", None, "h", "Binne")]),
 dict(id="aanmeld-qr", title="Aanmeld met 'n QR-kode", who="Leerder, alumnus, ouer", summary="Die admin wys 'n lewendige kode; die leerder skandeer dit binne die sirkel.",
  nodes=[scr("a", "p-qr-admin", 0, 0, [('#qr-box', "Lewendige kode")], "Admin by die ingang"),
         scr("b", "p-qr-idle", 1, 0, [('[data-action="start-scan"]', "Begin skandeer")], "Leerder: Kaart ▸ QR"),
         box("c", "q", 2, 0, "Geldige kode en binne die sirkel?", "Die foon kyk eerste, die bediener weer."),
         scr("d", "p-qr-ok", 3, 0, [('#scan-card', "Aangemeld")], "Ja"),
         scr("e", "p-qr-err", 3, 1, [('#scan-card', "Te ver")], "Nee: geweier"),
         scr("f", "p-qr-queued", 3, 2, [('#scan-card', "Gestoor")], "Geen internet")],
  edges=[("a", 0, "b", "Skandeer"), ("b", 0, "c", "Begin skandeer"), ("c", None, "d", "Ja"), ("c", None, "e", "Nee"), ("c", None, "f", "Offline")]),
 dict(id="nooi", title="Nooi en antwoord", who="Admin nooi; leerder antwoord", summary="'n Uitnodiging gee toegang; aanvaar bespreek dadelik.",
  nodes=[scr("a", "p-admin-ev2", 0, 0, [('[data-action="invite-open"]', "Nooi")], "Geleentheid (admin)"),
         scr("b", "p-nooi", 1, 0, [('[name="grades"]', "Grade"), ('#groups-box', "Groepe"), ('[name="emails"]', "E-posse"), ('[data-form="invite"] [type="submit"]', "Stuur uitnodigings")], "Kies wie"),
         scr("c", "p-nooi-done", 2, 0, [('.card', "Resultaat")], "Hoeveel genooi"),
         box("d", "push", 3, 0, "Push: Uitnodiging", "Net nuwe genooides."),
         scr("e", "p-inbox", 4, 0, [('.inbox-item [data-accept="1"]', "Aanvaar / Weier")], "Leerder: Inbox"),
         scr("f", "p-ev-invited", 4, 1, [('[data-action="answer-invite"][data-accept="1"]', "Aanvaar / Weier")], "Of op die geleentheid"),
         scr("g", "p-myprogram-acc", 5, 0, [('.mine-grid [data-event]', "Bespreek")], "Aanvaar"),
         box("h", "admin", 6, 0, "Admin sien dit", "Telling en Excel-kolom Uitnodiging.")],
  edges=[("a", 0, "b", "Nooi"), ("b", 3, "c", "Stuur"), ("c", None, "d", ""), ("d", None, "e", ""), ("d", None, "f", ""), ("e", 0, "g", "Aanvaar"), ("g", None, "h", "")]),
 dict(id="groep", title="Iemand by 'n groep voeg", who="Departement-admin, Hoof-admin", summary="Soek op naam en kies uit die dropdown, of plak e-posse.",
  nodes=[scr("a", "p-bestuur", 0, 0, [('[data-action="open-group"]', "Bestuur (groep)")], "Bestuur"),
         scr("b", "p-groep", 1, 0, [('#person-search', "Soek iemand"), ('[data-action="add-person"]:not([disabled])', "+ Voeg by"), ('[data-form="add-members"]', "Of plak e-posse")], "Groep"),
         box("c", "db", 2, 0, "Lid gestoor", ""),
         box("d", "inbox", 3, 0, "Inbox: Jy is bygevoeg", "Plus push."),
         scr("e", "p-groep-done", 2, 1, [('[data-action="remove-member"]', "Lede-lys")], "Lys bygewerk")],
  edges=[("a", 0, "b", "Bestuur"), ("b", 1, "c", "+ Voeg by"), ("c", None, "d", ""), ("c", None, "e", "")]),
 dict(id="volg", title="Volg afdelings en groepe", who="Almal", summary="Bepaal of jy 'Nuwe geleentheid'-boodskappe van 'n afdeling of groep kry.",
  nodes=[scr("a", "p-instellings", 0, 0, [('[data-page="follow"]', "Wat ek volg")], "Instellings"),
         scr("b", "p-volg", 1, 0, [('[data-action="toggle-follow-dept"]', "Afdeling aan/af"), ('[data-action="toggle-group"]', "Oop groep aan/af"), ('.pill', "Privaat: net admins")], "Wat ek volg"),
         box("c", "db", 2, 0, "Gestoor", "Niemand anders sien wat jy volg nie (net admins sien hul eie afdeling se volgers)."),
         box("d", "inbox", 3, 0, "Volgende nuwe geleentheid", "Jy kry dit as die admin volgers of die groep kies.")],
  edges=[("a", 0, "b", "Tik"), ("b", 0, "c", ""), ("c", None, "d", "")]),
 dict(id="kennisgewings", title="Kennisgewings aanskakel", who="Almal", summary="Die app vra ná aanmelding; jy kan dit later in Instellings doen.",
  nodes=[scr("a", "p-pushask", 0, 0, [('#push-ask [data-yes]', "Skakel aan")], "Ná aanmelding"),
         scr("a2", "p-instellings", 0, 1, [('#push-card', "Of hier")], "Of in Instellings"),
         box("b", "phone", 1, 0, "Foon vra: Allow?", "Op iPhone net vanaf die tuisskerm."),
         box("c", "db", 2, 0, "Toestel geregistreer", "Hoogstens 10 toestelle per persoon."),
         scr("d", "p-instellings-on", 3, 0, [('#push-card', "Aan · Stuur toets")], "Aan")],
  edges=[("a", 0, "b", "Skakel aan"), ("a2", 0, "b", ""), ("b", None, "c", "Allow"), ("c", None, "d", "")]),
 dict(id="kalender", title="Kalender koppel", who="Almal", summary="Jou besprekings in jou foon se kalender (Apple, Google, Outlook); veranderings kom vanself.",
  nodes=[scr("a", "p-cal-off", 0, 0, [('[data-action="cal-toggle"]', "Skakel aan")], "Instellings ▸ Kalender"),
         box("b", "db", 1, 0, "Privaat skakel gemaak", "Net vir jou; wie dit het, sien jou besprekings."),
         scr("c", "p-cal-on", 2, 0, [('#cal-card a[href^="webcal"]', "Apple-kalender"), ('#cal-card a[href*="google"]', "Google-kalender"), ('[data-action="cal-copy"]', "Kopieer (Outlook)")], "Kies jou kalender"),
         box("d", "ext", 3, 0, "Kalender-app teken in", "Een keer per toestel."),
         box("e", "ok", 4, 0, "Besprekings in jou kalender", "Apple werk elke uur by, Google elke paar uur: nuwe besprekings, veranderings en kansellasies."),
         box("f", "q", 2, 1, "Skakel af", "Die skakel werk nie meer nie."),
         box("g", "bad", 3, 1, "Geleenthede verdwyn", "By die volgende bywerking; verwyder die Garsie Army-kalender in jou kalender-app.")],
  edges=[("a", 0, "b", "Aan"), ("b", None, "c", ""), ("c", 0, "d", "Tik"), ("d", None, "e", ""), ("f", None, "g", "")]),
 dict(id="tuisskerm", title="Sit op tuisskerm", who="Almal op 'n foon", summary="Nodig vir kennisgewings op iPhone; die app bly ingeteken.",
  nodes=[scr("a", "p-install", 0, 0, [('[data-phone="iphone"]', "iPhone of Android")], "Kies jou foon"),
         scr("b", "p-install-iphone", 1, 0, [], "Die stappe (iPhone)"),
         box("c", "phone", 2, 0, "Ikoon op tuisskerm", "Maak die app van daar oop.")],
  edges=[("a", 0, "b", "Kies"), ("b", 0, "c", "")]),
 dict(id="skrap", title="Skrap my rekening", who="Almal (nie die laaste Hoof-admin nie)", summary="Vee alles van die persoon uit; kan nie ongedaan gemaak word nie.",
  nodes=[scr("a", "p-instellings", 0, 0, [('[data-action="delete-account"]', "Skrap my rekening")], "Instellings"),
         scr("b", "p-delete", 1, 0, [('#delete-account [data-yes]', "Bevestig")], "Seker?"),
         box("c", "db", 2, 0, "Alles uitgevee", "Profiel, besprekings, uitnodigings, aanmeldings, Inbox, toestelle."),
         scr("d", "p-signin", 3, 0, [], "Terug by aanmelding")],
  edges=[("a", 0, "b", "Tik"), ("b", 0, "c", "Ja"), ("c", None, "d", "")]),
 dict(id="leerder", title="Leerder regstel", who="Hoof-admin", summary="Leerders kan nie self hul naam, graad of geslag verander nie.",
  nodes=[scr("a", "p-key-instellings", 0, 0, [('[data-page="learner"]', "Verander 'n leerder")], "Instellings"),
         scr("b", "p-leerder-edit", 1, 0, [('[data-form="find-learner"]', "Soek op e-pos"), ('[data-form="edit-learner"] [type="submit"]', "Stoor")], "Regstel"),
         box("c", "db", 2, 0, "Gestoor", "Die bediener laat dit net vir 'n Hoof-admin toe.")],
  edges=[("a", 0, "b", "Tik"), ("b", 1, "c", "Stoor")]),
 dict(id="aansig", title="Leerder-aansig", who="Hoof-admin", summary="Sien die app soos 'n leerder van 'n gekose graad; niks word gestoor nie.",
  nodes=[scr("a", "p-key-instellings", 0, 0, [('[data-page="preview"]', "Leerder-aansig")], "Instellings"),
         scr("b", "p-preview", 1, 0, [('[data-form="start-preview"] [type="submit"]', "Begin")], "Kies graad en geslag"),
         scr("c", "p-preview-on", 2, 0, [('#preview-banner', "Goue strook · Verlaat")], "Aansig aan")],
  edges=[("a", 0, "b", "Tik"), ("b", 0, "c", "Begin")]),
 dict(id="jaar", title="Elke jaar: graad op", who="Bediener (outomaties)", summary="Op 1 Januarie gaan almal een graad op; Graad 12 word Alumni.",
  nodes=[box("a", "phone", 0, 0, "1 Januarie, net ná middernag", "Bediener se klok."),
         box("b", "db", 1, 0, "Graad 8 → 9 … 11 → 12", ""),
         box("c", "db", 2, 0, "Graad 12 → Alumni", ""),
         box("d", "ok", 3, 0, "Wie mag kom pas outomaties", "Leerders sien die regte geleenthede vir hul nuwe graad.")],
  edges=[("a", None, "b", ""), ("b", None, "c", ""), ("c", None, "d", "")]),
]

used = sorted({n['shot'] for p in PROCS for n in p['nodes'] if n['kind'] == 'screen'})
shots = []
for sid in used:
    setup, full, post = SHOTS[sid]
    sels = []
    for p in PROCS:
        for n in p['nodes']:
            if n['kind'] == 'screen' and n['shot'] == sid:
                for sel, _ in n['marks']:
                    if sel not in sels: sels.append(sel)
    typ = None
    if post.startswith('TYPE:'):
        _, sel, val = post.split(':', 2); typ = [sel, val]; post = ''
    shots.append(dict(id=sid, setup=setup, full=full, post=post, type=typ, sels=sels, wait=2200 if 'kaart' in sid else 700))
json.dump({"procs": PROCS, "shots": shots}, open(os.path.join(D, 'procs.json'), 'w', encoding='utf-8'), ensure_ascii=False, indent=1)
print(len(PROCS), "processes;", len(shots), "screens")
